name : infra deployment via githubActions

on:
  push:
    branches:
    - main

jobs:
 terraform : 
   name: Terraform Plan & Apply
   runs-on: ubuntu-latest
   

   
   env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

   steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: parent_module
        run: terraform init

      - name: Terraform Validate
        working-directory: parent_module
        run: terraform validate

      - name: Terraform Plan
        working-directory: parent_module
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: parent_module
        run: terraform apply -auto-approve tfplan 
